name: Deploy to Firebase on schedule

on:
  schedule:
    # Runs every hour from 7 AM to 8 PM (7:00, 9:00, 10:00, ..., 19:00, 20:00) on weekdays
    - cron: '0 6-20 * * 1-5'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Uninstall Firebase CLI
        run: npm uninstall -g firebase-tools
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.6.0  # workaround fix
      
      - name: Install project dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use crssnt-prod
          firebase experiments:enable webframeworks
          firebase deploy --only hosting:aktien-crssnt
